# Generated by Django 2.1.1 on 2018-10-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0002_remove_beds_idrefb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='idRef',
        ),
    ]
