# Generated by Django 2.1.1 on 2018-10-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beds',
            name='idRefB',
        ),
    ]
