# Generated by Django 2.1.1 on 2018-10-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0003_remove_temperature_idref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartrate',
            name='heartRate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
