# Generated by Django 2.1.1 on 2018-10-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0004_auto_20181023_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idEmployee', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=45)),
                ('middleName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('contactNum', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('usertype', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
    ]
