# Generated by Django 2.1.1 on 2018-10-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unodosmattress', '0005_auto_20181027_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(max_length=45),
        ),
    ]
