# Generated by Django 2.0.5 on 2018-09-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBed', '0002_auto_20180920_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beds',
            name='idBeds',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='idHeartRate',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='idPatient',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient_table',
            name='idPatientTable',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='idPosition',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ref_bedstatus',
            name='idRef_BedStatus',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ref_heartrate',
            name='idRef_HeartRate',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ref_temp',
            name='idRef_Temp',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='idTemperature',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='idThreshold',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
