# Generated by Django 2.0.5 on 2018-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBed', '0003_auto_20180920_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='idThreshold',
        ),
        migrations.AddField(
            model_name='patient',
            name='maxHeartRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='maxTemp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='minHeartRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='minTemp',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Threshold',
        ),
    ]
