# Generated by Django 2.0.5 on 2018-09-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageBed', '0006_auto_20180925_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('idBeds', models.AutoField(primary_key=True, serialize=False)),
                ('bedNumber', models.IntegerField(default=0)),
                ('bedStatus', models.CharField(max_length=45)),
                ('idRefB', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('idHeartRate', models.AutoField(primary_key=True, serialize=False)),
                ('heartRate', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idPatient', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=45)),
                ('middleName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('birthdate', models.DateField()),
                ('religion', models.CharField(max_length=45)),
                ('minTemp', models.IntegerField(default=0)),
                ('maxTemp', models.IntegerField(default=0)),
                ('minHeartRate', models.IntegerField(default=0)),
                ('maxHeartRate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Table',
            fields=[
                ('idPatientTable', models.AutoField(primary_key=True, serialize=False)),
                ('idBeds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageBed.Beds')),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageBed.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('idPosition', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=45)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageBed.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ref_BedStatus',
            fields=[
                ('idRef_BedStatus', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_HeartRate',
            fields=[
                ('idRef_HeartRate', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('minHeartRate', models.IntegerField(default=0)),
                ('maxHeartRate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Temp',
            fields=[
                ('idRef_Temp', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('minTemp', models.IntegerField(default=0)),
                ('maxTemp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('idTemperature', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageBed.Patient')),
                ('idRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageBed.Ref_Temp')),
            ],
        ),
        migrations.AddField(
            model_name='heartrate',
            name='idPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageBed.Patient'),
        ),
        migrations.AddField(
            model_name='heartrate',
            name='idRefHeart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageBed.Ref_HeartRate'),
        ),
    ]
