# Generated by Django 2.0.5 on 2018-09-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBed', '0007_auto_20180925_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_PatientStatus',
            fields=[
                ('idRef_PatientStatus', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
