# Generated by Django 2.0.5 on 2018-09-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageBed', '0009_auto_20180925_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birthdate',
            new_name='birthDate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
    ]
