# Generated by Django 2.0.5 on 2018-09-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBed', '0016_auto_20180928_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartrate',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
