# Generated by Django 2.0.5 on 2018-09-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBed', '0018_auto_20180928_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartrate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='time',
            field=models.TimeField(),
        ),
    ]
