# Generated by Django 2.0.5 on 2018-10-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBed', '0019_auto_20180928_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('idDoctor', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=45)),
                ('middleName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('contactNum', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='bedNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='contactNum',
            field=models.IntegerField(default=0),
        ),
    ]
