# Generated by Django 2.0.5 on 2018-10-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBed', '0021_auto_20181004_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contactNum',
            field=models.CharField(max_length=11),
        ),
    ]
