# Generated by Django 2.0.5 on 2018-10-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageBed', '0022_auto_20181006_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
